# Change these first
owner: gitlimes # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: limes.pink
    url: https://limes.pink
  - name: microsoftgithub.com
    url: https://microsoftgithub.com/usage
  - name: Discord Markdown Badge (back-end)
    url: https://dcbadge.limes.pink/md-shield/json?u=406125028065804289
  - name: Discord Markdown Badge (renderer)
    url: https://dcbadge.vercel.app/
  - name: fedi.limes.pink (fedi instance)
    url: https://fedi.limes.pink/@limes
  - name: cors.limes.pink (personal cors-proxy)
    url: https://cors.limes.pink
  - name: stats server (this page)
    url: https://stats.limes.pink/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.limes.pink
  # baseUrl: /your-repo-name
  logoUrl: https://limes.pink/assets/images/fursona_stilldefinitelynotafurrythough.png
  name: limes.pink
  introTitle: "Hey, I'm ash! I make stuff™"
  introMessage: This status page lets you check if it works or not.
  theme: "night"
  favicon: https://limes.pink/assets/favicons/favicon-16x16.png
