# Change these first
owner: gitlimes # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: limes.pink
    url: https://limes.pink
  - name: Discord Markdown Badge (user endpoint + renderer)
    url: https://dcbadge.vercel.app/api/shield/406125028065804289
  - name: Discord Markdown Badge (server endpoint + renderer)
    url: https://dcbadge.vercel.app/api/server/zkspfFwqDg
  - name: (^._.^) cat server (hosts the dcbadge backend and statistics)
    url: https://cat.limes.pink/
  - name: statistics server
    url: https://stats.limes.pink/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.limes.pink
  # baseUrl: /your-repo-name
  logoUrl: https://limes.pink/assets/images/transspinmii.gif
  name: limes.pink
  introTitle: "Hey, I'm ash! I make stuff™"
  introMessage: This status page lets you check if it works or not.
  themeUrl: https://cdn.statically.io/gh/gitlimes/status/master/assets/pruble.css
  favicon: https://limes.pink/assets/favicons/favicon-16x16.png
